sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pmagas/docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true pmagas/docker-react-ci npm run test
