sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pmagas/docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true pmagas/docker-react-ci npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'docker-react-ci'
  env: 'DockerReactCi-env'
  bucket_name: "elasticbeanstalk-ap-southeast-2-605313441167"
  bucket_path: 'docker-react-ci'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY