sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pmagas/docker-react-ci -f Docskerfile.dev .

script:
  - docker run -e CI=true pmagas/docker-react-ci npm run test


deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_name: "elasticbeanstalk-ap-southeast-2-605313441167"
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY